# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-bfe945e9e91d44ef91e7b22c66b4805f
      model-name: qwen-max
      log-requests: true
      log-responses: true
      max-tokens: 8192
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-bfe945e9e91d44ef91e7b22c66b4805f
      model-name: qwen-max
      max-tokens: 8192
      log-requests: true
      log-responses: true


# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://ai-code-screenshots-1317259809.cos.ap-nanjing.myqcloud.com
    secretId: AKIDBGG6jGahaFn8GAqJYdVBeuxmOmwtd9lA
    secretKey: EE3g6JJ6f082iDapumTxEIXcU9aoqfGd
    region: ap-nanjing
    bucket: ai-code-screenshots-1317259809

